// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin-dashboard/Dashboard.tsx": () => import("../components/mockups/admin-dashboard/Dashboard.tsx"),
  "./components/mockups/delivery-section/DeliverySection.tsx": () => import("../components/mockups/delivery-section/DeliverySection.tsx"),
  "./components/mockups/footer-white/Footer.tsx": () => import("../components/mockups/footer-white/Footer.tsx"),
  "./components/mockups/shipping-containers/ContainersMarquee.tsx": () => import("../components/mockups/shipping-containers/ContainersMarquee.tsx"),
  "./components/mockups/swiftship-logo/FooterLogo.tsx": () => import("../components/mockups/swiftship-logo/FooterLogo.tsx"),
  "./components/mockups/swiftship-logo/NavbarLogo.tsx": () => import("../components/mockups/swiftship-logo/NavbarLogo.tsx")
};
